CREATE TABLE IF NOT EXISTS mapping_frames (
    id BIGSERIAL PRIMARY KEY,
    frame_id BIGINT NOT NULL,
    timestamp_ns BIGINT NOT NULL DEFAULT (
        (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000000000)::BIGINT
    ),
    pose_x DOUBLE PRECISION NOT NULL,
    pose_y DOUBLE PRECISION NOT NULL,
    pose_z DOUBLE PRECISION NOT NULL,
    yaw DOUBLE PRECISION NOT NULL,
    point_count INTEGER NOT NULL,
    processing_latency_ms DOUBLE PRECISION,
    fps DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS spatial_cells (
    grid_x INTEGER NOT NULL,
    grid_y INTEGER NOT NULL,
    resolution_band SMALLINT NOT NULL,
    elevation_min DOUBLE PRECISION NOT NULL,
    elevation_max DOUBLE PRECISION NOT NULL,
    elevation_mean DOUBLE PRECISION NOT NULL,
    point_count INTEGER NOT NULL,
    resolution DOUBLE PRECISION NOT NULL,
    terrain_class TEXT NOT NULL DEFAULT 'unknown',
    class_name TEXT NOT NULL DEFAULT 'unknown',
    confidence REAL NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (grid_x, grid_y, resolution_band)
);

ALTER TABLE spatial_cells ADD COLUMN IF NOT EXISTS elevation_min DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE spatial_cells ADD COLUMN IF NOT EXISTS elevation_max DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE spatial_cells ADD COLUMN IF NOT EXISTS elevation_mean DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE spatial_cells ADD COLUMN IF NOT EXISTS point_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE spatial_cells ADD COLUMN IF NOT EXISTS terrain_class TEXT NOT NULL DEFAULT 'unknown';

CREATE TABLE IF NOT EXISTS detected_objects (
    id BIGSERIAL PRIMARY KEY,
    frame_id BIGINT NOT NULL,
    object_id BIGINT NOT NULL,
    class_name TEXT NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    z DOUBLE PRECISION NOT NULL,
    width DOUBLE PRECISION NOT NULL,
    length DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    confidence REAL NOT NULL,
    dynamic BOOLEAN NOT NULL DEFAULT FALSE
);
